### PR TITLE
Update CSRA viper seed

### PR DESCRIPTION
**Pull request by romidane**

### CODE REVIEW

**Comment by glenjamin** [comment]
Are these numbers related to some remote system, or are they just made up?

If they're just made up, we should follow https://dsdmoj.atlassian.net/wiki/spaces/AAT/pages/187629618/NOMS+ID+Validation+Rules to use numbers that will never be used on the real system

**Comment by romidane** [comment]
@glenjamin they are numbers I selected from NOMIS on the move that are in their staging environment... I asked them which one are the ones they are the least likely to delete and these are the ones they gave me.

**Comment by glenjamin** [comment]
Makes sense, could you add a comment into the seeds file to that effect?

Also i think some tests need updating to match.

**Comment by romidane** [comment]
@glenjamin I think Snyk is complaing .. there is a PR to address those issues I believe..  Add the comment

**Comment by mattonfoot** [comment]
have rerun without the cached dependencies and snyk passes but there is now a db issue

**Pull request merged**
